PetrolPumpSystem/Controllers/MachineReadingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PetrolPumpSystem.Models;

namespace PetrolPumpSystem.Controllers
{
    public class MachineReadingsController : Controller
    {
        private PetrolPumpDBEntities db = new PetrolPumpDBEntities();

        // GET: MachineReadings
        public ActionResult Index()
        {
            var tblMachineReadings = db.tblMachineReadings.Include(t => t.Machine);
            return View(tblMachineReadings.ToList());
        }

        // GET: MachineReadings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblMachineReading tblMachineReading = db.tblMachineReadings.Find(id);
            if (tblMachineReading == null)
            {
                return HttpNotFound();
            }
            return View(tblMachineReading);
        }

        // GET: MachineReadings/Create
        public ActionResult Create()
        {
            ViewBag.MachineId = new SelectList(db.Machines, "MachinId", "MachineName");
            return View();
        }

        // POST: MachineReadings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MReadingId,StartReading,EndingReading,ReadingDate,MachineId")] tblMachineReading tblMachineReading)
        {
            if (ModelState.IsValid)
            {
                db.tblMachineReadings.Add(tblMachineReading);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MachineId = new SelectList(db.Machines, "MachinId", "MachineName", tblMachineReading.MachineId);
            return View(tblMachineReading);
        }

        // GET: MachineReadings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblMachineReading tblMachineReading = db.tblMachineReadings.Find(id);
            if (tblMachineReading == null)
            {
                return HttpNotFound();
            }
            ViewBag.MachineId = new SelectList(db.Machines, "MachinId", "MachineName", tblMachineReading.MachineId);
            return View(tblMachineReading);
        }

        // POST: MachineReadings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MReadingId,StartReading,EndingReading,ReadingDate,MachineId")] tblMachineReading tblMachineReading)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblMachineReading).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MachineId = new SelectList(db.Machines, "MachinId", "MachineName", tblMachineReading.MachineId);
            return View(tblMachineReading);
        }

        // GET: MachineReadings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblMachineReading tblMachineReading = db.tblMachineReadings.Find(id);
            if (tblMachineReading == null)
            {
                return HttpNotFound();
            }
            return View(tblMachineReading);
        }

        // POST: MachineReadings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblMachineReading tblMachineReading = db.tblMachineReadings.Find(id);
            db.tblMachineReadings.Remove(tblMachineReading);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PetrolPumpSystem/Views/MachineReadings/Create.cshtml
@model PetrolPumpSystem.Models.tblMachineReading

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="SubPageHeader">
    <div class="row">
        <div class="col-sm-12"> 
            <h4 style="float:left;">Machines</h4>
        </div>
    </div>
</div>
<br />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartReading,"Start Reading", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.StartReading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartReading, "", new { @class = "text-danger" })
            </div>
       
            @Html.LabelFor(model => model.EndingReading,"Ending Reading", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.EndingReading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndingReading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReadingDate,"Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ReadingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReadingDate, "", new { @class = "text-danger" })
            </div>
      
            @Html.LabelFor(model => model.MachineId, "Machine", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("MachineId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MachineId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success"/>
            </div>
        </div>
    </div>
}

<div class="subPageMargin">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetrolPumpSystem/Views/MachineReadings/Delete.cshtml
@model PetrolPumpSystem.Models.tblMachineReading

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblMachineReading</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartReading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartReading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndingReading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndingReading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReadingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReadingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Machine.MachineName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Machine.MachineName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PetrolPumpSystem/Views/MachineReadings/Details.cshtml
@model PetrolPumpSystem.Models.tblMachineReading

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblMachineReading</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartReading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartReading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndingReading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndingReading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReadingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReadingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Machine.MachineName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Machine.MachineName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MReadingId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PetrolPumpSystem/Views/MachineReadings/Edit.cshtml
@model PetrolPumpSystem.Models.tblMachineReading

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblMachineReading</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MReadingId)

        <div class="form-group">
            @Html.LabelFor(model => model.StartReading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartReading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartReading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndingReading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndingReading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndingReading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReadingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReadingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReadingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MachineId, "MachineId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MachineId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MachineId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetrolPumpSystem/Views/MachineReadings/Index.cshtml
@model IEnumerable<PetrolPumpSystem.Models.tblMachineReading>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="SubPageHeader">
    <div class="row">
        <div class="col-sm-12">
            <h4 style="float:left;">Machines Readings</h4>
            <h4 style="float:right;margin-right:2em;">Total Suppliers: @Session["totalSuppliers"]</h4>
        </div>
    </div>
</div>
<br />
<p class="subPageMargin">
    @*@Html.ActionLink("Add New", "Create")*@
    <input type="button" class="btn btn-success" value="Add New" onclick="location.href='@Url.Action("Create", "MachineReadings")'" />

</p>
<div class="container table-responsive">
    <table class="table table-responsive table-striped " id="myTable">
        <thead>
            <tr class="tblHeader">
                <th>
                    Start Reading
                </th>
                <th>
                    Ending Reading
                </th>
                <th>
                    Date
                </th>
                <th>
                    Machine
                </th>
                <th>Actions</th>
            </tr>
            </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="tblbody">
                    <td>
                        @Html.DisplayFor(modelItem => item.StartReading)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndingReading)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReadingDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Machine.MachineName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.MReadingId }, new { @class = "btn btn-primary btn-sm" })


                        @*@Html.ActionLink("Edit", "Edit", new { id = item.MReadingId }) |
                        @Html.ActionLink("Details", "Details", new { id = item.MReadingId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.MReadingId })*@
                    </td>
                </tr>
            }
        </tbody>
    </table>
    </div>