PetrolPumpSystem/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PetrolPumpSystem.Models;

namespace PetrolPumpSystem.Controllers
{
    public class PurchasesController : Controller
    {
        private PetrolPumpDBEntities db = new PetrolPumpDBEntities();

        // GET: Purchases
        public ActionResult Index()
        {
            var tblPurchases = db.tblPurchases.Include(t => t.tblProduct).Include(t => t.tblSupplier);
            return View(tblPurchases.ToList());
        }

        // GET: Purchases/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPurchase tblPurchase = db.tblPurchases.Find(id);
            if (tblPurchase == null)
            {
                return HttpNotFound();
            }
            return View(tblPurchase);
        }

        // GET: Purchases/Create
        public ActionResult Create()
        {
            ViewBag.PId = new SelectList(db.tblProducts, "PId", "PName");
            ViewBag.SupId = new SelectList(db.tblSuppliers, "SupId", "SupName");
            return View();
        }

        // POST: Purchases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PurchId,SupId,PId,TankerNo,PurchQuantity,PurchPrice,Unit,PurchDate")] tblPurchase tblPurchase)
        {
            if (ModelState.IsValid)
            {
                db.tblPurchases.Add(tblPurchase);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PId = new SelectList(db.tblProducts, "PId", "PName", tblPurchase.PId);
            ViewBag.SupId = new SelectList(db.tblSuppliers, "SupId", "SupName", tblPurchase.SupId);
            return View(tblPurchase);
        }

        // GET: Purchases/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPurchase tblPurchase = db.tblPurchases.Find(id);
            if (tblPurchase == null)
            {
                return HttpNotFound();
            }
            ViewBag.PId = new SelectList(db.tblProducts, "PId", "PName", tblPurchase.PId);
            ViewBag.SupId = new SelectList(db.tblSuppliers, "SupId", "SupName", tblPurchase.SupId);
            Session["pqty"] = tblPurchase.PurchQuantity;
            return View(tblPurchase);
        }

        // POST: Purchases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PurchId,SupId,PId,TankerNo,PurchQuantity,PurchPrice,Unit,PurchDate")] tblPurchase tblPurchase)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblPurchase).State = EntityState.Modified;
                db.SaveChanges();
                double qtyOnEdit = tblPurchase.PurchQuantity;
                double qtyBeforeEdit = (double)Session["pqty"];
                double qtytotal = qtyOnEdit - qtyBeforeEdit;
                var row = db.tblStocks.FirstOrDefault(x => x.PId == tblPurchase.PId);
                row.StQuantity = (row.StQuantity + qtytotal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PId = new SelectList(db.tblProducts, "PId", "PName", tblPurchase.PId);
            ViewBag.SupId = new SelectList(db.tblSuppliers, "SupId", "SupName", tblPurchase.SupId);
            return View(tblPurchase);
        }

        // GET: Purchases/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPurchase tblPurchase = db.tblPurchases.Find(id);
            if (tblPurchase == null)
            {
                return HttpNotFound();
            }
            return View(tblPurchase);
        }

        // POST: Purchases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblPurchase tblPurchase = db.tblPurchases.Find(id);
            db.tblPurchases.Remove(tblPurchase);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PetrolPumpSystem/Views/Purchases/Create.cshtml
@model PetrolPumpSystem.Models.tblPurchase

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="SubPageHeader">
    <div class="row">
        <div class="col-sm-12">
            <h4 style="float:left;">Add new Purchase</h4>
            <h4 style="float:right;margin-right:2em;">Total Fuels: @Session["totalfuels"]</h4>
        </div>
    </div>
</div>
<br />


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SupId, "SupId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("SupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupId, "", new { @class = "text-danger" })
            </div>
      
            @Html.LabelFor(model => model.PId, "PId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("PId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TankerNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.TankerNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TankerNo, "", new { @class = "text-danger" })
            </div>
     
            @Html.LabelFor(model => model.PurchQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PurchQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PurchPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchPrice, "", new { @class = "text-danger" })
            </div>
     
            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="subPageMargin">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetrolPumpSystem/Views/Purchases/Delete.cshtml
@model PetrolPumpSystem.Models.tblPurchase

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblPurchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TankerNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TankerNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblProduct.PName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblProduct.PName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSupplier.SupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSupplier.SupName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PetrolPumpSystem/Views/Purchases/Details.cshtml
@model PetrolPumpSystem.Models.tblPurchase

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblPurchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TankerNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TankerNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblProduct.PName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblProduct.PName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSupplier.SupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSupplier.SupName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PurchId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PetrolPumpSystem/Views/Purchases/Edit.cshtml
@model PetrolPumpSystem.Models.tblPurchase

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="SubPageHeader">
    <div class="row">
        <div class="col-sm-12">
            <h4 style="float:left;">Edit Purchase</h4>
            <h4 style="float:right;margin-right:2em;">Total Fuels: @Session["totalfuels"]</h4>
        </div>
    </div>
</div>
<br />



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PurchId)

        <div class="form-group">
            @Html.LabelFor(model => model.SupId, "SupId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("SupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupId, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.PId, "PId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("PId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TankerNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.TankerNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TankerNo, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.PurchQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PurchQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PurchPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchPrice, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetrolPumpSystem/Views/Purchases/Index.cshtml
@model IEnumerable<PetrolPumpSystem.Models.tblPurchase>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="SubPageHeader">
    <div class="row">
        <div class="col-sm-12">
            <h4 style="float:left;">Prchases</h4>
            <h4 style="float:right;margin-right:2em;">Total Fuels: @Session["totalfuels"]</h4>
        </div>
    </div>
</div>
<br />
<p class="subPageMargin">
    @*@Html.ActionLink("Add New", "Create")*@
    <input type="button" class="btn btn-success" value="Add New" onclick="location.href='@Url.Action("Create", "Purchases")'" />

</p>
<div class="container table-responsive">
    <table class="table table-responsive table-striped " id="myTable">
        <thead>
            <tr class="tblHeader">
                <th>
                    Supplier:
                </th>
                <th>
                    Fuel
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Unit
                </th>
                <th>
                    Rate:
                </th>
                <th>
                    Truck No
                </th>
                <th>
                    Date
                </th>
                <th>Actions</th>
            </tr>
            </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr class="tblbody">
                    <td>
                        @Html.DisplayFor(modelItem => item.tblSupplier.SupName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tblProduct.PName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PurchQuantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Unit)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PurchPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TankerNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PurchDate)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.PurchId }, new { @class = "btn btn-primary btn-sm" })
                        @*@Html.ActionLink("Details", "Details", new { id = item.PurchId }, new { @class = "btn btn-primary btn-sm" })*@ 
                      
                    </td>
                </tr>
            }
        </tbody>

    </table>
    </div>